### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by motasimhussain** [faceair/atom-goto-definition#14]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [goto-definition](https://github.com/faceair/atom-goto-definition) package, v1.1.18
### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /C:/Users/Motasim/.atom/packages/goto-definition/lib/goto-definition.coffee:54

TypeError: Cannot read property 'split' of undefined
    at Object.module.exports.getScanOptions (file:///C:/Users/Motasim/.atom/packages/goto-definition/lib/goto-definition.coffee:49:45)
    at Object.module.exports.go (file:///C:/Users/Motasim/.atom/packages/goto-definition/lib/goto-definition.coffee:73:23)
    at atom-text-editor.<anonymous> (file:///C:/Users/Motasim/.atom/packages/goto-definition/lib/goto-definition.coffee:31:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
     -6:15.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-improved-chester-atom-syntax.theme-one-dark-ui)
     -0:02.5.0 goto-definition:go (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "quantum-shell",
      "esformatter"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "one-dark-ui",
      "improved-chester-atom-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.0
atom-jade, v0.3.0
autoclose-html, v0.23.0
autocomplete-modules, v1.5.2
codeigniter, v0.3.0
emmet, v2.4.3
fonts, v1.6.0
goto-definition, v1.1.18
highlight-selected, v0.11.2
improved-chester-atom-syntax, v0.2.0
javascript-snippets, v1.2.1
language-typescript-grammars-only, v1.5.0
linter, v1.11.14
linter-csslint, v1.3.2
linter-htmlhint, v1.2.1
linter-jshint, v2.1.0
open-recent, v5.0.0
php-cs-fixer, v2.5.6
pigments, v0.31.2
project-plus, v0.9.0
Remote-FTP, v0.8.3
rest-client, v1.2.0
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by faceair** [comment]
What did you do before throwing this error?
And I released an new version, maybe it have been fixed.

**Comment by rouquin** [comment]
I've also just received this error.

I have a fresh install of Atom 1.9.8, no other 3rd party packages are installed (it really is that fresh), build 1.1.19 of the goto-definition package. Mac OS X 10.10.5.

My use case to produce the error is...
1. edit a ruby file
2. highlight a method call
3. right click and select goto definition, or hit cmd-alt-enter 

[EDIT] The issue happens when copying and pasting ruby code into a new file tab in Atom, i.e. file not saved anywhere on disk. If I save the ruby code to a file everything works fine.

**Comment by HansVaider0815** [comment]
> The issue happens when copying and pasting ruby code into a new file tab in Atom, i.e. file not saved anywhere on disk. If I save the ruby code to a file everything works fine.

Same for PHP

**Comment by faceair** [comment]
I reproduce the error. When new file not save, we can't get the filename and it's language. So, I will disable the function in this scene.
