### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by dundee** [faceair/atom-goto-definition#3]
**Atom Version**: 1.5.3
**System**: linux 4.4.1-2-ARCH
**Thrown From**: [goto-definition](https://github.com/faceair/atom-goto-definition) package, v1.1.10
### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /home/dundee/.atom/packages/goto-definition/lib/goto-definition.coffee:72

TypeError: Cannot read property '0' of undefined
    at /home/dundee/.atom/packages/goto-definition/lib/goto-definition.coffee:72:32
    at Array.map (native)
    at /home/dundee/.atom/packages/goto-definition/lib/goto-definition.coffee:68:30
    at Workspace.module.exports.Workspace.scan (/usr/share/atom/resources/app.asar/src/workspace.js:938:11)
    at Object.module.exports.go (/home/dundee/.atom/packages/goto-definition/lib/goto-definition.coffee:67:20)
    at atom-text-editor.<anonymous> (/home/dundee/.atom/packages/goto-definition/lib/goto-definition.coffee:31:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:544:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:363:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -2:05.4.0 core:delete (atom-text-editor.editor.is-focused)
     -2:05.1.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -2:04.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:03.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:30.7.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:29.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:27.7.0 goto-definition:go (atom-text-editor.editor.is-focused)
     -1:25.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 29x -1:23.6.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:21.1.0 goto-definition:go (atom-text-editor.editor.is-focused)
     -0:48.7.0 core:cancel (a.stack-toggle)
     -0:44.8.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
 22x -0:37.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:15.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:15.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:06.4.0 goto-definition:go (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-python, v1.6.1
custom-title, v1.0.1
file-icons, v1.6.14
goto-definition, v1.1.10
highlight-selected, v0.11.2
linter, v1.11.3
linter-flake8, v1.10.1
linter-pep8, v1.2.1
minimap, v4.19.0
project-manager, v2.7.6
tree-ignore, v0.6.1

# Dev
No dev packages
```

**Comment by faceair** [comment]
What did you do before throwing this error ? Is it frequent?

**Comment by dundee** [comment]
It looks like it happens when (Python):

1) go to definition of A
2) accidentaly add one line before A (causes warning by pep8)
3) go again to definiton of A - error appears

**Comment by dundee** [comment]
The same happens when I move definition of A in the file.
It looks like there is some cache of position of A and it does not work when A is moved.

**Comment by faceair** [comment]
Maybe it is Atom's bug. https://github.com/atom/atom/issues/10900

I have a dirty fix. Can you help me verify my patch is work ?
Just do this:
1. open Settings-> Packages -> Goto Definition -> View Code
2. replace lib/goto-definition.coffee lines, like [this](https://github.com/faceair/atom-goto-definition/commit/793c02dec456fecbabfbd01f02c67ad47b266703)
3. reload the window.

If it work, I will release a new version.

**Comment by dundee** [comment]
Yes, it works now. Thanks!

**Comment by faceair** [comment]
How can this `2) accidentaly add one line before A (causes warning by pep8)` be done ?

If you lost focus on goto-definition panel, this scan should be canceled. Do you think so ?

**Comment by dundee** [comment]
2) this can be any change which will move A in file, but without saving.

I'am not sure what you mean.

**Comment by faceair** [comment]
Is this operation in Atom ?
If you edit another file, you must lost focus on goto-definition panel. And the scan should be canceled.

**Comment by dundee** [comment]
Yes, it is.

I have two files: b.py and a.py, there is B extended from A in b.py and A in a.py

1) open b.py and goto definition (ctrl+alt+enter) of A - works
2) change position of A in a.py, but do not save the file
3) open b.py again and goto definition of A - fails with error

**Comment by faceair** [comment]
Oh, because my `auto save` opton is open ...

**Comment by faceair** [comment]
Cheers! 🍻

```
➜  atom-goto-definition git:(master) apm publish 1.1.11
Preparing and tagging a new version ✓
Pushing v1.1.11 tag ✓
Publishing goto-definition@v1.1.11 ✓
```

**Comment by dundee** [comment]
Great, thanks!
