### ISSUE TITLE
Failed to load the goto-definition package

### ISSUE THREAD

**Issue by sovanjana** [faceair/atom-goto-definition#39]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [goto-definition](https://github.com/faceair/atom-goto-definition) package 1.2.0

### Stack Trace

Failed to load the goto-definition package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (~/AppData/Local/atom/app-1.14.4/resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/goto-definition/node_modules/space-pen/lib/space-pen.js:9:18)
  at /packages/goto-definition/node_modules/space-pen/lib/space-pen.js:634:4)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/goto-definition/node_modules/atom-space-pen-views/lib/main.js:4:10)
  at /packages/goto-definition/node_modules/atom-space-pen-views/lib/main.js:22:4)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/goto-definition/lib/definitions-view.coffee:3:1)
  at /packages/goto-definition/lib/definitions-view.coffee:3:1)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/goto-definition/lib/goto-definition.coffee:1:19)
  at /packages/goto-definition/lib/goto-definition.coffee:1:1)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
  at /app.asar/src/package.js:123:28
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
  at /app.asar/src/package-manager.js:412:19
  at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
  at /app.asar/src/atom-environment.js:794:28

```

### Commands

```
     -0:43.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-ternjs 0.18.1 
autoclose-html 0.23.0 
autocomplete-modules 1.6.7 
editorconfig 2.2.2 
es6-javascript 1.0.0 
file-icons 2.0.17 
git-plus 7.3.1 
goto-definition 1.2.0 
javascript-snippets 1.2.1 
language-babel 2.55.6 
linter 1.11.23 
linter-eslint 8.1.2 
linter-htmlhint 1.3.1 
linter-jshint 3.0.2 
minimap 4.26.8 
react 0.16.2 
seti-ui 1.6.1 
```

**Comment by faceair** [comment]
Maybe something error, can you reinstall this package ? Just `apm uninstall goto-definition` and `apm install goto-definition`.
