### ISSUE TITLE
Uncaught Error: Invalid child node: undefined

### ISSUE THREAD

**Issue by ikzjfr0** [faceair/atom-goto-definition#66]
together with this: https://github.com/tgandrews/atom-easy-jsdoc/issues/55

after installing atom-easy-jsdoc, and this problem comes

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [goto-definition](https://github.com/faceair/atom-goto-definition) package 1.3.3

### Stack Trace

Uncaught Error: Invalid child node: undefined

```
At /Users/liangwang/.atom/packages/goto-definition/node_modules/atom-select-list/node_modules/etch/lib/dom.js:25

Error: Invalid child node: undefined
  at Object.dom (/packages/goto-definition/node_modules/atom-select-list/node_modules/etch/lib/dom.js:25:15)
  at /app.asar/node_modules/incompatible-packages/lib/incompatible-packages-component.js:203:31
  at Array.map (native)
  at IncompatiblePackagesComponent.renderIncompatibleModules (/app.asar/node_modules/incompatible-packages/lib/incompatible-packages-component.js:199:34)
  at IncompatiblePackagesComponent.renderIncompatiblePackage (/app.asar/node_modules/incompatible-packages/lib/incompatible-packages-component.js:152:63)
  at Array.map (native)
  at IncompatiblePackagesComponent.renderIncompatiblePackageList (/app.asar/node_modules/incompatible-packages/lib/incompatible-packages-component.js:128:35)
  at IncompatiblePackagesComponent.render (/app.asar/node_modules/incompatible-packages/lib/incompatible-packages-component.js:79:14)
  at updateSync (/packages/goto-definition/node_modules/atom-select-list/node_modules/etch/lib/component-helpers.js:99:34)
  at /packages/goto-definition/node_modules/atom-select-list/node_modules/etch/lib/component-helpers.js:72:7
  at DefaultScheduler.performUpdates (/packages/goto-definition/node_modules/atom-select-list/node_modules/etch/lib/default-scheduler.js:48:34)

```

### Commands

```
     -0:05.5.0 incompatible-packages:view (div.incompatible-packages-status.inline-block.text.text-error)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
ask-stack 2.2.0 
atom-beautify 0.29.23 
atom-bracket-highlight 0.3.2 
atom-clock 0.1.7 
atom-easy-jsdoc 4.12.1 
atom-html-preview 0.1.22 
atom-material-syntax 1.0.2 
atom-runner 2.7.1 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-modules 1.6.9 
autocomplete-python 1.8.63 
base64 0.3.0 
browser-plus 0.0.87 
busy-signal 1.4.1 
color-picker 2.2.5 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.4 
fonts 2.0.0 
git-control 0.9.0 
git-plus 7.8.0 
git-time-machine 1.5.9 
goto-definition 1.3.3 
highlight-selected 0.13.1 
Hydrogen 1.12.1 
intentions 1.1.2 
language-babel 2.58.0 
language-swift 0.5.0 
linter 2.1.4 
linter-eslint 8.1.7 
linter-ui-default 1.3.0 
linter-write-good 0.9.0 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
node-debugger 1.10.1 
nucleus-dark-ui 0.12.1 
nuclide 0.223.0 
open-recent 5.0.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
prettier-atom 0.30.0 
pretty-json 1.6.3 
project-manager 3.3.4 
regex-railroad-diagram 0.17.0 
script 3.14.1 
split-diff 1.3.1 
terminal-plus 0.14.5 
```

**Comment by dundee** [comment]
Hack to fix this: 

Install latest version of incompatible-packages:

```
apm install incompatible-packages
```

Then rebuild incompatible packages (git-blame in my case) and then you can uninstall again:

```
apm uninstall incompatible-packages
```
